apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ansible

resources:
  # - ./ns.yaml
  - ./vi.yaml
  - ./overlays/vm-01
  # - ./overlays/vm-02
  # - ./overlays/vm-03

configurations:
- transformer.yaml
