apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ansible

resources:
  - ./ns.yaml
  - ./vm.yaml
  - ./vd-root.yaml
  - ./vi.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: cloud-init-ansible-demo
    files:
      - userdata=cfg/cloudinit.yaml
    type: provisioning.virtualization.deckhouse.io/cloud-init
