apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./vm.yaml
  - ./vd.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: cloud-init-demo-vm
    files:
      - userdata=cfg/cloudinit.yaml
    type: provisioning.virtualization.deckhouse.io/cloud-init
