apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- awx.yaml
- cert.yaml
- pvc-pass.yaml
- pvc-prj.yaml
- pg.yaml

secretGenerator:
- name: awx-postgres-configuration
  literals:
  - host=d8ms-pg-awx-rw
  - port=5432
  - database=awx
  - username=awx
  - password=secretawx
  - sslmode=disable

generatorOptions:
  disableNameSuffixHash: true
